ci:
    autoupdate_schedule: 'weekly'
    autofix_prs: true

repos:
-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black-jupyter
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
